sudo: false
language: node_js
env:
  - CXX="g++-4.8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
node_js:
  - "8"
#  - "7"
#  - "6"
#  - "4"
script:
  - istanbul cover ./node_modules/.bin/grunt --report lcovonly && istanbul report text && ( cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true ) && rm -rf coverage
  - ./node_modules/chromedriver/bin/chromedriver --url-base=/wd/hub --port=4444 &
  - ./node_modules/.bin/wdio wdio.conf.js
before_script:
  - npm install -g istanbul
  - npm install coveralls
  - npm install webdriverio
  - npm install chromedriver
